/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tabungan.view;

import com.tabungan.controller.DashboardController;
import com.tabungan.model.Dashboard;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.tabungan.view.ViewTambahTabungan;

/**
 *
 * @author radik
 */
public class DashboardView extends javax.swing.JFrame {

    private String username;

    /**
     * Creates new form DashboardView
     */
    public DashboardView(String username) {
        initComponents();
        this.username = username;
        setTitle("Dashboard Tabungan - " + username); // Tambahkan nama pengguna ke judul
        DashboardController dashboardController = new DashboardController();
        loadDataToTable(dashboardController, username);
        lblUsername.setText("" + username);
    }

    public void refresh() {
        DashboardController dashboardController = new DashboardController();
        loadDataToTable(dashboardController, username); // Perbarui data di tabel
    }

    public void loadDataToTable(DashboardController dashboardController, String username) {
        // Ambil model dari tabel
        DefaultTableModel model = (DefaultTableModel) tblTabungan.getModel();

        // Hapus semua data yang ada di tabel (jika ada)
        model.setRowCount(0);

        // Ambil data tabungan dari controller berdasarkan username
        List<Dashboard> daftarTabungan = dashboardController.ambilSemuaTabungan(username);

        // Tambahkan setiap data tabungan ke tabel
        for (Dashboard dashboard : daftarTabungan) {
            // Hitung persentase pencapaian
            double persentase = (dashboard.getTotalTerkumpul() / dashboard.getTargetTabungan()) * 100;

            // Tambahkan baris baru ke tabel
            model.addRow(new Object[]{
                dashboard.getNamaTabungan(), // Nama Tabungan
                dashboard.getTargetTabungan(), // Target
                dashboard.getTotalTerkumpul(), // Total Terkumpul
                String.format("%.2f%%", persentase) // Pencapaian dalam persen
            });
        }
    }

    private String getSelectedNamaTabungan() {
        int selectedRow = tblTabungan.getSelectedRow();
        if (selectedRow != -1) {
            return tblTabungan.getValueAt(selectedRow, 0).toString(); // Kolom 0 = Nama Tabungan
        }
        JOptionPane.showMessageDialog(this, "Silakan pilih tabungan yang ingin diupdate!");
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabungan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtNominal = new javax.swing.JTextField();
        btnAddNominal = new javax.swing.JButton();
        lblNominal = new javax.swing.JLabel();
        lblNominal3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNominal1 = new javax.swing.JLabel();
        btnTambahTabungan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblNominal2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaTabunganBaru = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTargetTabunganBaru = new javax.swing.JTextField();
        lblNominal4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LOGOUT");

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGO");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama aplikasi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBack)
                .addGap(157, 157, 157)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(15, 15, 15))
        );

        tblTabungan.setBackground(new java.awt.Color(204, 204, 255));
        tblTabungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Tabungan", "Target", "Total Terkumpul", "Pencapaian"
            }
        ));
        jScrollPane1.setViewportView(tblTabungan);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        txtNominal.setBackground(new java.awt.Color(255, 255, 255));
        txtNominal.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        txtNominal.setForeground(new java.awt.Color(204, 204, 204));
        txtNominal.setText("Masukan nominal tabungan");

        btnAddNominal.setBackground(new java.awt.Color(204, 204, 255));
        btnAddNominal.setText("+");
        btnAddNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNominalActionPerformed(evt);
            }
        });

        lblNominal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNominal.setForeground(new java.awt.Color(255, 255, 255));
        lblNominal.setText("Tambahkan Nominal Tabungan");

        lblNominal3.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblNominal3.setForeground(new java.awt.Color(255, 255, 255));
        lblNominal3.setText("* Pilih tabungan yang ada di dalam daftar tabungan");

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNominal3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblNominal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNominal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNominal3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddNominal)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNominal)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Selamat datang di kelola tabungan,");

        lblUsername.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 153, 255));
        lblUsername.setText("username");

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        lblNominal1.setBackground(new java.awt.Color(255, 255, 255));
        lblNominal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNominal1.setForeground(new java.awt.Color(255, 255, 255));
        lblNominal1.setText("Buat Tabungan Baru");

        btnTambahTabungan.setBackground(new java.awt.Color(204, 204, 255));
        btnTambahTabungan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTambahTabungan.setText("+");
        btnTambahTabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahTabunganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahTabungan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblNominal1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNominal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahTabungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hapus ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("DAFTAR TABUNGAN");

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        lblNominal2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNominal2.setForeground(new java.awt.Color(255, 255, 255));
        lblNominal2.setText("Perbarui Rincian Tabungan");

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(255, 255, 255)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Nama Tabungan  ");

        txtNamaTabunganBaru.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaTabunganBaru.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNamaTabunganBaru.setText("Masukan nama tabungan baru");
        txtNamaTabunganBaru.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNamaTabunganBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaTabunganBaruActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Target ");

        txtTargetTabunganBaru.setBackground(new java.awt.Color(255, 255, 255));
        txtTargetTabunganBaru.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtTargetTabunganBaru.setText("Masukan nominal target baru");
        txtTargetTabunganBaru.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTargetTabunganBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTargetTabunganBaruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaTabunganBaru)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTargetTabunganBaru))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaTabunganBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTargetTabunganBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblNominal4.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblNominal4.setForeground(new java.awt.Color(255, 255, 255));
        lblNominal4.setText("* Pilih tabungan yang akan di perbarui  di dalam daftar tabungan");

        btnUpdate.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate.setForeground(new java.awt.Color(153, 153, 153));
        btnUpdate.setText("Perbarui");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblNominal4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNominal2)
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(95, 95, 95))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNominal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNominal4)
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(144, 144, 144)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNominalActionPerformed
       // Ambil baris yang dipilih dari tabel
    int row = tblTabungan.getSelectedRow();

    if (row >= 0) {
        // Ambil nama tabungan dari tabel
        String namaTabungan = (String) tblTabungan.getValueAt(row, 0);

        try {
            // Ambil nominal dari input pengguna
            double nominal = Double.parseDouble(txtNominal.getText());

            if (nominal <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Nominal harus lebih besar dari 0.",
                        "Kesalahan Input",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Tambahkan nominal melalui controller
            DashboardController dashboardController = new DashboardController();
            boolean berhasil = dashboardController.tambahNominal(namaTabungan, nominal);

            if (berhasil) {
                JOptionPane.showMessageDialog(this,
                        "Nominal berhasil ditambahkan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);

                // Update nilai total terkumpul di model tabel secara langsung
                double totalTerkumpul = (double) tblTabungan.getValueAt(row, 2); // Kolom 2 = Total Terkumpul
                totalTerkumpul += nominal; // Tambahkan nominal ke total terkumpul

                tblTabungan.setValueAt(totalTerkumpul, row, 2); // Update model tabel
                
                // Hitung persentase pencapaian dan update kolom pencapaian
                double targetTabungan = (double) tblTabungan.getValueAt(row, 1); // Kolom 1 = Target
                double persentase = (totalTerkumpul / targetTabungan) * 100;
                tblTabungan.setValueAt(String.format("%.2f%%", persentase), row, 3); // Kolom 3 = Pencapaian
                
                txtNominal.setText(""); // Bersihkan field nominal
            } else {
                JOptionPane.showMessageDialog(this,
                        "Gagal menambahkan nominal. Silakan coba lagi.",
                        "Kesalahan",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Masukkan nominal dalam format angka yang valid.",
                    "Kesalahan Input",
                    JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this,
                "Pilih salah satu tabungan dari tabel untuk menambahkan nominal.",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnAddNominalActionPerformed

    private void btnTambahTabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahTabunganActionPerformed
        // TODO add your handling code here:
        ViewTambahTabungan tambahTabunganView = new ViewTambahTabungan(username, DashboardView.this);
        tambahTabunganView.setVisible(true); // Tampilkan form tambah tabungan
    }//GEN-LAST:event_btnTambahTabunganActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTabungan.getSelectedRow(); // Cek baris yang dipilih
    if (selectedRow != -1) { // Jika ada baris yang dipilih
        String namaTabungan = tblTabungan.getValueAt(selectedRow, 0).toString(); // Ambil nama tabungan
        
        // Konfirmasi penghapusan
        int response = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus tabungan " + namaTabungan + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            // Panggil metode hapus tabungan di DashboardController
            DashboardController dashboardController = new DashboardController();
            boolean isDeleted = dashboardController.hapusTabungan(namaTabungan);
            
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Tabungan berhasil dihapus!");
                refresh(); // Refresh tabel setelah berhasil hapus
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus tabungan!");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih tabungan yang ingin dihapus!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNamaTabunganBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaTabunganBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaTabunganBaruActionPerformed

    private void txtTargetTabunganBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargetTabunganBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetTabunganBaruActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblTabungan.getSelectedRow(); // Cek baris yang dipilih di tabel
    if (selectedRow != -1) { // Jika ada baris yang dipilih
        String oldNamaTabungan = tblTabungan.getValueAt(selectedRow, 0).toString(); // Kolom 0 = Nama Tabungan
        String newNamaTabungan = txtNamaTabunganBaru.getText(); // Ambil input dari txtNamaTabunganBaru
        String targetString = txtTargetTabunganBaru.getText(); // Ambil input dari txtTargetTabunganBaru

        if (newNamaTabungan.isEmpty() || targetString.isEmpty()) { // Validasi input tidak boleh kosong
            JOptionPane.showMessageDialog(this, "Nama tabungan dan target tidak boleh kosong!");
            return;
        }

        try {
            double newTargetTabungan = Double.parseDouble(targetString); // Konversi target menjadi double

            // Buat instance dari DashboardController
            DashboardController dashboardController = new DashboardController();
            boolean isUpdated = dashboardController.updateTabungan(oldNamaTabungan, newNamaTabungan, newTargetTabungan);

            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Tabungan berhasil diperbarui!");
                refresh(); // Refresh tabel setelah berhasil update
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui tabungan!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Target tabungan harus berupa angka!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih tabungan yang ingin diupdate!");
    }
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ViewTabunganMenu tabunganMenuView = new ViewTabunganMenu(username);
        tabunganMenuView.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String username = null;
                new DashboardView(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNominal;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTambahTabungan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNominal;
    private javax.swing.JLabel lblNominal1;
    private javax.swing.JLabel lblNominal2;
    private javax.swing.JLabel lblNominal3;
    private javax.swing.JLabel lblNominal4;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblTabungan;
    private javax.swing.JTextField txtNamaTabunganBaru;
    private javax.swing.JTextField txtNominal;
    private javax.swing.JTextField txtTargetTabunganBaru;
    // End of variables declaration//GEN-END:variables
}
